name: Release

on:
  push:
    branches:
      - master
      - beta
      - alpha

jobs:
  release:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2
        with:
          fetch-depth: 0
          persist-credentials: false

      - name: Setup Node
        uses: actions/setup-node@v2
        with: 
          node-version: '15.x'

      - name: Install dependencies
        run: npm ci

      - name: Build
        run: |
          npm run build
          cd ./dist
          zip ../dist.zip * **/*

      - uses: actions/upload-artifact@v2
        with:
          name: dist
          path: ./dist

      - name: Release
        uses: cycjimmy/semantic-release-action@v2
        id: release
        with:
          semantic_version: 17
        env:
          GITHUB_TOKEN: ${{ secrets.GH_TOKEN }}

      - name: Announce to Discord
        if: steps.release.outputs.new_release_published == 'true'
        run: |
          curl \
            -X POST \
            -H 'Content-Type: application/json' \
            -d '{ "content": "@everyone, version ${{ steps.release.outputs.new_release_version }} is now available! [Check it out!](https://alpha.repeatedpleasant.games)" }' \
            ${{ secrets.DISCORD_WEBHOOK_URL }}
